In [1]:
import numpy as np
queue = np.zeros((10))

head = 0
tail = 0

In [2]:
class Queue(object):

  head = 0

  tail = 0

  q = []


  def __init__(self, size):

    self.size = size

    self.q = np.zeros((self.size))

    self.__item = 0


  def setItem(self, item):

    self.__item = item


  def enqueue(self):

    if (self.tail + 1) % self.size ==  self.head:

      print('Queue is full!!!')

    else:

      self.q[self.tail] = self.__item

      self.tail = (self.tail + 1) % self.size 

      print(self.q)

      print('Queue tail at index: {}'.format(self.tail))

  def dequeue(self):

    if self.head == self.tail:

      print('Queue is empty!!!')

    else:

      print('{} is removed'. format(self.q[self.head]))

      self.q[self.head] = 0

      print(self.q)
    
      self.head = (self.head + 1) % self.size 


      print('Queue head at index: {}'.format(self.head))


In [3]:
qu = Queue(5)

for i in range(100,105):

  qu.setItem(i)

  qu.enqueue()


[100.   0.   0.   0.   0.]
Queue tail at index: 1
[100. 101.   0.   0.   0.]
Queue tail at index: 2
[100. 101. 102.   0.   0.]
Queue tail at index: 3
[100. 101. 102. 103.   0.]
Queue tail at index: 4
Queue is full!!!


In [4]:
for i in range(3):

  qu.dequeue()

100.0 is removed
[  0. 101. 102. 103.   0.]
Queue head at index: 1
101.0 is removed
[  0.   0. 102. 103.   0.]
Queue head at index: 2
102.0 is removed
[  0.   0.   0. 103.   0.]
Queue head at index: 3


In [5]:
for i in range(2,6):

  qu.setItem(i)

  qu.enqueue()

[  0.   0.   0. 103.   2.]
Queue tail at index: 0
[  3.   0.   0. 103.   2.]
Queue tail at index: 1
[  3.   4.   0. 103.   2.]
Queue tail at index: 2
Queue is full!!!


In [6]:
for i in range(5):
  
  qu.dequeue()

103.0 is removed
[3. 4. 0. 0. 2.]
Queue head at index: 4
2.0 is removed
[3. 4. 0. 0. 0.]
Queue head at index: 0
3.0 is removed
[0. 4. 0. 0. 0.]
Queue head at index: 1
4.0 is removed
[0. 0. 0. 0. 0.]
Queue head at index: 2
Queue is empty!!!
